SELECT * FROM PLACES
WHERE HOST_ID IN (
SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(ID) >= 2
    ) ORDER BY ID ASC

-- 코드를 입력하세요
SELECT PLACES.* FROM 
    PLACES,
    (SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID) >= 2) AS HOST
WHERE PLACES.HOST_ID = HOST.HOST_ID ORDER BY ID

SELECT * FROM PLACES WHERE HOST_ID IN 
    (SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID) >= 2)
ORDER BY ID;
    